import type { ImageSourcePropType } from 'react-native';

import { getHomeRoleLabel, type HomeRoleId } from './home-role-config';

export type FeedCard = {
  author: string;
  body: string[];
  cover: ImageSourcePropType;
  coverGradient: [string, string];
  featured?: boolean;
  featuredBadge?: string;
  id: string;
  publishDate: string;
  roleId: HomeRoleId;
  roleLabel: string;
  sourceUrl: string;
  time: string;
  title: string;
  views: string;
};

const REMOTE_IMAGES = {
  backendRack: {
    uri: 'https://images.pexels.com/photos/5480781/pexels-photo-5480781.jpeg?auto=compress&cs=tinysrgb&w=1200',
  },
  careerNotebook: {
    uri: 'https://images.pexels.com/photos/5124877/pexels-photo-5124877.jpeg?auto=compress&cs=tinysrgb&w=1200',
  },
  circuitBoard: {
    uri: 'https://images.pexels.com/photos/2182863/pexels-photo-2182863.jpeg?auto=compress&cs=tinysrgb&w=1200',
  },
  codeWorkspace: {
    uri: 'https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg?auto=compress&cs=tinysrgb&w=1200',
  },
} satisfies Record<string, ImageSourcePropType>;

function buildFeedCard(card: Omit<FeedCard, 'roleLabel'>): FeedCard {
  return {
    ...card,
    roleLabel: getHomeRoleLabel(card.roleId),
  };
}

export const FEED_CARDS: FeedCard[] = [
  buildFeedCard({
    id: 'cpp-visual-studio',
    roleId: 'cpp',
    featured: true,
    featuredBadge: 'C++ 进阶',
    title: '想走 C++ 开发，先把编译、导航、断点调试这一套走顺',
    author: '微软 C++ 团队博客',
    views: '2.4k',
    time: '6m',
    publishDate: '2017-04-21',
    sourceUrl: 'https://devblogs.microsoft.com/cppblog/getting-started-with-visual-studio-for-c-and-cpp-development/',
    cover: REMOTE_IMAGES.codeWorkspace,
    coverGradient: ['rgba(217, 236, 255, 1)', 'rgba(185, 230, 239, 1)'],
    body: [
      '这篇文章一上来先把 Visual Studio 对 C++ 开发者的定位讲得很明确：它不是单纯写代码的编辑器，而是一整套从代码编写、编译构建、调试诊断、测试到团队协作都覆盖到的 IDE。作者特别提到，不管你是刚开始写程序的学生，还是已经做过一段时间 C++ 的开发者，都能在这里找到适合自己的工作方式。对求职者来说，这一点很重要，因为企业真正看重的也从来不只是语法本身，而是你有没有在一套完整的工程环境里把事情做通。',
      '在安装部分，原文重点介绍了 Community、Professional、Enterprise 三个版本，以及安装器里的不同 workload。文章建议初学者至少把 Desktop development with C++ 装好，因为它直接决定了你能否顺利创建、编译和调试本地 C++ 项目。这里传递出的核心信息是：C++ 开发环境不是“随便装个 IDE”就结束了，正确的组件、编译器、调试工具和模板本身就是开发流程的一部分。',
      '接着作者讲到项目组织方式。Visual Studio 里的代码通常会围绕 Solution 和 Project 展开，`.sln` 和 `.vcxproj` 这些文件不只是格式问题，它们还承担着配置编译选项、包含路径、依赖关系等职责。文章同时也提到 Open Folder 和 CMake 支持，说明现代 C++ 项目不一定都只能靠传统工程文件驱动，但无论哪种方式，你都需要理解“代码如何被组织、如何被构建”。这对做项目表达时非常关键，因为它直接影响你在面试里能不能把工程结构讲清楚。',
      '构建和排错这一段写得很实际。作者让读者先尝试 Build Solution，再故意面对一个编译错误，然后借助 Output Window 和 Error List 去定位问题。原文想强调的是，写 C++ 项目时，编译报错并不是异常情况，而是日常开发的一部分。关键不是“有没有错误”，而是你会不会读报错、能不能迅速跳到定位点、能不能用错误列表和输出信息判断问题属于语法、配置还是依赖。对初学者来说，这比单纯练习语言题目更接近真实开发。',
      '在代码编辑与导航部分，文章依次介绍了 IntelliSense、Go To、Peek Definition、Rename 等能力。它给出的示例都非常贴近日常工作：通过自动补全查看可用函数，通过 Ctrl+T 快速跳文件和符号，通过 F12 或 Alt+F12 看定义，再通过重命名重构统一修改接口名。作者想传达的其实是工程效率观念。一个成熟开发者不会靠肉眼翻文件，也不会在多文件项目里手动搜改所有名字，而是依赖工具去提高理解速度和修改准确度。',
      '后面的调试、测试和协作章节则把这条链路补完整了。文章通过 breakpoint、Autos Window、Step Over、Step Into 等示例说明了如何理解程序运行时状态；又通过 Native Unit Test Project 展示了怎样在 Visual Studio 里给原生 C++ 项目加单元测试；最后还介绍了如何把项目接入 Git 并推送到 GitHub。整篇文章真正有价值的地方，不是教你背快捷键，而是让你看到一个完整的 C++ 开发闭环：环境搭好、项目打开、代码能改、错误能查、逻辑能调、结果能测、多人能协作。这种闭环能力，恰好就是 C++ 岗位最想看到的东西。',
    ],
  }),
  buildFeedCard({
    id: 'cpp-code-navigation',
    roleId: 'cpp',
    title: '写 C++ 项目时，理解代码和快速跳转往往比敲代码更重要',
    author: '微软 C++ 团队博客',
    views: '2.1k',
    time: '5m',
    publishDate: '2017-04-20',
    sourceUrl: 'https://devblogs.microsoft.com/cppblog/c-code-editing-and-navigation-in-visual-studio/',
    cover: REMOTE_IMAGES.codeWorkspace,
    coverGradient: ['rgba(228, 237, 255, 1)', 'rgba(205, 240, 242, 1)'],
    body: [
      '这篇文章的核心观点很鲜明：多数开发者其实花在“看代码、理解代码、定位代码”的时间，比真正敲代码还要多，所以一个成熟的 C++ 工作流必须把阅读和导航效率放到足够高的位置。Visual Studio 提供的很多能力，例如语法高亮、错误波浪线、Quick Info、Parameter Info、类视图和调用层级，本质上都在解决“如何更快理解一个已有工程”的问题，而不只是帮助你写新代码。',
      '原文在“Reading and Understanding Code”部分花了不少笔墨介绍如何借助编辑器去理解大型项目，比如 Scroll Bar Map Mode 可以从整体上看文件结构，Class View 可以从项目维度看符号树，Generate Graph of Include Files 和 View Call Hierarchy 则有助于梳理依赖和调用链。对做 C++ 的人来说，这类工具很有现实意义，因为 C++ 项目天然更容易出现多文件、多头文件和深层调用关系，如果没有好的导航方式，单是读懂已有代码就会消耗大量精力。',
      '在导航部分，文章几乎把日常开发中最常用的路径都列了一遍：Open Document、Toggle Header / Code File、Solution Explorer、Go To Definition、Find in Files、Find All References、Navigation Bar、Quick Launch。它想说明的并不是“快捷键越多越厉害”，而是任何一个能快速切到目标符号、目标文件、目标引用位置的动作，都会直接缩短理解和修改代码的时间。尤其在 C++ 场景下，头文件和实现文件来回切换是高频动作，这种效率差距会被放得很大。',
      '文章后半段则把视角切到了“编辑与重构”。IntelliSense、Quick Fixes、Rename、Change Function Signature、EditorConfig 这些功能，被放在同一条线上讲清楚：写 C++ 并不意味着所有改动都要靠手工维护。真正成熟的开发方式，是借助工具去完成一致性修改、风格约束和结构化重构。对求职者来说，这篇文章非常值得转化成自己的工程表达，因为它能帮你把“我会写 C++”升级成“我知道怎样在一个复杂 C++ 项目里高效理解、导航、修改和维护代码”。',
    ],
  }),
  buildFeedCard({
    id: 'cpp-debugging-diagnostics',
    roleId: 'cpp',
    title: '调试能力决定 C++ 项目推进速度，断点只是最基础的一层',
    author: '微软 C++ 团队博客',
    views: '1.8k',
    time: '6m',
    publishDate: '2017-04-10',
    sourceUrl: 'https://devblogs.microsoft.com/cppblog/c-debugging-and-diagnostics/',
    cover: REMOTE_IMAGES.codeWorkspace,
    coverGradient: ['rgba(225, 233, 255, 1)', 'rgba(214, 243, 232, 1)'],
    body: [
      '这篇文章从一开始就把调试放到了很高的位置上。作者说 debugging 是软件开发的基石之一，而且往往会占据开发者一天里相当大的一部分时间。Visual Studio 的 native debugger 功能很强，但也正因为功能太多，新手很容易只会最浅的一层。原文写这篇文章的目的，就是帮 C++ 开发者建立一个完整的调试视角：不仅知道怎么停下来，更要知道怎么观察、怎么诊断、怎么在复杂场景里定位问题。',
      '在 breakpoints 和 control flow 这一部分，文章先从最基础的 F5、断点和控制执行流讲起。这一段最有价值的地方在于它提醒读者，调试不只是为了“看一眼变量”，而是为了控制程序执行上下文，决定自己要在哪个函数、哪条路径、哪个时间点停下来观察状态。换句话说，断点的意义在于帮你建立问题定位路径，而不是单纯充当暂停键。',
      '原文后面还继续覆盖了 data inspection、diagnostic tools、performance profiling、debugging processes and devices、multi-threaded debugging、edit and continue 等主题。它实际上是在告诉开发者，项目复杂度一旦上去，问题就不会只出在单线程、单模块、单进程里。你很可能会遇到多线程状态错乱、远程调试、设备调试、性能瓶颈这类情况，而调试器应该被当成一整套问题分析系统来使用。',
      '对你想投的 C++ 岗来说，这篇文章的意义尤其直接。很多同学做项目时只会“代码报错就改到能跑”，但一到面试，真正能拉开差距的是你能不能描述一套调试方法：如何设置断点、如何看当前状态、如何缩小怀疑范围、如何处理线程和性能问题。原文给出的这些工具视角，非常适合被吸收进你的项目复盘里。这样你对外展示的就不只是“项目做出来了”，而是“我知道问题是怎么被调出来、分析出来并修掉的”。',
    ],
  }),
  buildFeedCard({
    id: 'cpp-year-of-improvements',
    roleId: 'cpp',
    title: '真正拉开 C++ 工程效率差距的，往往是构建、诊断和跨平台工具链',
    author: '微软 C++ 团队博客',
    views: '2.6k',
    time: '6m',
    publishDate: '2024-02-12',
    sourceUrl: 'https://devblogs.microsoft.com/cppblog/a-year-of-cpp-improvements-in-visual-studio-vs-code-and-vcpkg/',
    cover: REMOTE_IMAGES.codeWorkspace,
    coverGradient: ['rgba(226, 237, 255, 1)', 'rgba(207, 241, 237, 1)'],
    body: [
      '这篇年度回顾很适合拿来理解现代 C++ 开发到底在往哪里演进。文章一开始就明确说，过去一年微软围绕 Visual Studio、VS Code、编译工具链和 vcpkg 做的大量改进，重点集中在 ARM64、Unreal、代码安全和跨平台开发上。也就是说，现在企业对 C++ 开发者的期待已经不只是“能把语法写对”，而是要能在复杂工具链里把开发效率、构建效率和代码可靠性一起拉起来。',
      '原文列出的改进点非常密集，但核心可以归成三类。第一类是跨平台开发能力，比如 Linux terminal、WSL 安装、Remote File Explorer、Remote Linux Unit Test、CMake Targets 和 CMake Debugger；第二类是日常工程效率，比如 Sticky Scroll、Brace Pair Colorization、Include Cleanup、结构化诊断、内存布局可视化；第三类是代码安全和性能，包括静态分析、Address Sanitizer、Build Insights、编译器优化等。它实际上展示的是一个完整 C++ 工程闭环，而不是某个零散工具功能。',
      '对学生尤其有启发的一点是，文章并没有把“工具进步”讲成纯粹的 IDE 更新日志，而是一直围绕真实开发问题展开。比如大项目里你需要看懂复杂嵌套代码，就会需要 Sticky Scroll；需要定位 include 导致的编译慢，就会需要 Build Insights；需要处理复杂宏、结构体布局和诊断信息，就会需要更强的可视化工具。换句话说，工具的价值来自工程痛点，而这恰恰是面试里非常容易被忽略、但很能体现成熟度的一块。',
      '如果你把 C++ 作为主投方向，这篇文章很适合转化成自己的准备思路。你不一定要把所有工具都用一遍，但至少要知道现代 C++ 项目常见的问题在哪：跨平台构建、调试、单元测试、代码安全、依赖管理、性能分析。只要你在项目里能有意识地展示其中两三项，面试官对你的评价就会明显不同，因为你表现出来的不是“只会写题”，而是“具备进入真实 C++ 工程环境的准备”。',
    ],
  }),
  buildFeedCard({
    id: 'cpp-cmake-support',
    roleId: 'cpp',
    title: '会写 CMake，才更像能接住现代 C++ 项目的开发者',
    author: '微软 C++ 团队博客',
    views: '1.9k',
    time: '5m',
    publishDate: '2016-10-05',
    sourceUrl: 'https://devblogs.microsoft.com/cppblog/cmake-support-in-visual-studio/',
    cover: REMOTE_IMAGES.codeWorkspace,
    coverGradient: ['rgba(233, 239, 255, 1)', 'rgba(214, 243, 240, 1)'],
    body: [
      '这篇文章最关键的一点，是它把 CMake 放到了现代 C++ 项目组织方式的中心位置。原文强调，Visual Studio 开始内建支持 CMake 项目之后，开发者不再需要每次都从命令行生成 VS solution 和 project 文件，而是可以直接围绕 CMakeLists.txt 做读取、编辑、配置、构建和调试。这背后传递出的信号很明确：今天很多真实的 C++ 项目，工程入口已经不再是 `.sln`，而是构建脚本本身。',
      '文章在“Getting started”里用一个最小示例说明了这种工作流：同目录放一个 cpp 文件和一个 CMakeLists.txt，然后直接 Open Folder。看起来非常简单，但意义很大，因为它意味着项目的构建定义和代码本身被绑在了一起，IDE 不再是唯一入口。对于想做 C++ 的学生来说，这一点必须尽快适应，因为许多跨平台或开源项目天然就是这种模式。',
      '原文后面列出的能力链也很完整：Reading C++ code、Editing C++ code、Editing CMake projects、Configuring CMake、Building CMake projects、Debugging、Target Linux、Opening multiple CMake projects。尤其有价值的是它提到 Visual Studio 会在你增删改源文件后自动重新执行 CMake configure，让 IntelliSense、构建和调试状态保持最新。作者其实是在说明，CMake 不是一个“额外负担”，而是帮助工程保持一致性的主线。',
      '把这篇内容放到你的首页帖子里，对求职准备的价值很直接。很多同学做 C++ 项目时，工程组织还停留在 IDE 模板级别，一旦切到 Linux 或要接开源库就开始乱。CMake 恰好是让你从“会写本地 demo”迈向“能管理真实工程”的关键节点。你不需要一上来就把 CMake 玩得很深，但至少要能读懂基础配置、能自己加源文件、能切构建目标、能解释为什么跨平台项目喜欢它。这样你的 C++ 路线才会更像企业真正需要的人。'
    ],
  }),
  buildFeedCard({
    id: 'backend-roadmap',
    roleId: 'backend',
    featured: true,
    featuredBadge: '后端主线',
    title: '后端岗位不只是会写接口，更关键的是数据库、API 和系统稳定性',
    author: 'roadmap.sh',
    views: '3.1k',
    time: '5m',
    publishDate: '2025-05-14',
    sourceUrl: 'https://roadmap.sh/backend',
    cover: REMOTE_IMAGES.backendRack,
    coverGradient: ['rgba(224, 237, 254, 1)', 'rgba(214, 229, 255, 1)'],
    body: [
      'roadmap.sh 在这篇内容里先给“后端开发”下了一个很直接的定义：后端是 Web 开发里偏服务端的一侧，重点负责服务器逻辑、数据库、API，以及用户请求的处理。原文特别把 authentication、authorization、request processing 这些词放在定义里，说明后端并不只是“把前端传来的东西存一下”，而是承担系统规则落地和数据安全控制的角色。你如果想投后端岗，第一步就要先把这个岗位的重心理解对。',
      '接着文章解释了后端开发者日常到底在做什么。它提到的关键词包括 server-side APIs、database operations、high traffic、external services、performance、scalability。换句话说，后端工程师不是只写业务逻辑，他还要面对数据库设计、接口稳定性、系统抗压能力，以及与支付、云服务等外部系统的集成。原文把后端形容成支撑前端体验的“backbone”，这一点特别贴切，因为很多用户看到的顺滑体验，本质上都来自背后服务端的设计和支撑。',
      '在“如何成为后端开发者”这一段，roadmap.sh 给出的路径非常典型，也非常适合新手照着拆。它建议先选一门后端语言，比如 Python、Ruby、Java、Go 之类，然后在理解语言基础之后，继续学这个语言对应的包管理器，接着补关系型数据库和最基本的 CRUD 操作。这个顺序很重要，因为它意味着后端学习不是东一榔头西一棒子，而是要先把语言、依赖、数据处理三块最基础的地基打牢。',
      '文章后面再进一步建议：可以再选一个 Web 框架，学着去构建一个简单的 RESTful API，并把最基本的认证授权也做进去。同时不要忽略 Git 和 GitHub，因为这些工具决定了你的代码能否被协作、被管理、被展示。原文还特别提醒，学习过程中要尽可能做项目，而不是只停留在看教程。这里实际上是在说，后端岗位的学习成果必须通过“能运行的服务”来证明，而不是靠背几个概念来证明。',
      '最后一部分则把求职落点说得很清楚。原文认为，在完成前面的基础后，就可以开始尝试申请入门级后端岗位，同时结合 roadmap 去查自己还有哪些短板没补齐。它还提到 degree 不是唯一门槛，portfolio、internship、networking 同样重要。也就是说，后端方向真正能拉开差距的，不是你有没有把整个路线图百分之百学完，而是你能不能把一部分关键能力做成项目、写进仓库、说进面试。对你来说，这种结构化路径尤其适合作为第二志愿去推进。',
    ],
  }),
  buildFeedCard({
    id: 'backend-developer-skills',
    roleId: 'backend',
    title: '后端能力不只是一门语言，数据库、API、测试和 Git 都要跟上',
    author: 'roadmap.sh',
    views: '2.7k',
    time: '6m',
    publishDate: '技能文章',
    sourceUrl: 'https://roadmap.sh/backend/developer-skills',
    cover: REMOTE_IMAGES.backendRack,
    coverGradient: ['rgba(224, 236, 255, 1)', 'rgba(202, 240, 248, 1)'],
    body: [
      '这篇文章和单纯的岗位介绍不一样，它不再解释“后端是什么”，而是直接把后端开发者需要补的核心能力列成一组清单。原文先强调一个前提：后端方向要求你保持长期学习的状态，因为语言、框架、库和方法论都在不断变化。也就是说，想做后端，不是学会一个框架就结束，而是要围绕核心能力持续打磨。',
      '在技能列表里，文章明确提到的重点包括编程语言、软件设计与架构、数据库管理、API 开发、版本控制、测试、CI/CD 与 DevOps 基础，以及 soft skills。这里最值得注意的是，它把 Git、Testing、CI/CD 和 Soft Skills 跟语言、数据库放在同一级别。作者想表达的是，后端岗真正考察的是一整条工程链，而不是某个单点技术。你可以从一门语言入手，但最后必须走向更完整的工程能力。',
      '原文对于语言和数据库的处理也很务实。它既提到 JavaScript、Python、Go、Java 这些常见后端语言，也在数据库部分区分了 SQL 与 NoSQL，并提醒读者理解 trade-off。到了 API、版本控制和测试部分，文章又回到日常工程：API 是后端工作的高频输出，Git 是协作的基本盘，而测试与调试则决定你能不能稳定维护系统。对于初学者来说，这种组织方式很有帮助，因为它把“后端能力图谱”展示得很完整。',
      '这篇内容非常适合你这种已经有一定工程实现基础、但还在收拢主线的人。它能帮助你判断后端方向还差哪些关键块没有补。比如你可能已经有 Linux、C++、调试和部分项目基础，那下一步就不该只盯着框架教程，而是应该按文章这套清单去补数据库、API、Git、测试和一点 CI/CD 思维。这样你的后端准备就不会散，而会越来越像一个真实岗位所需要的能力组合。',
    ],
  }),
  buildFeedCard({
    id: 'backend-server-side-intro',
    roleId: 'backend',
    title: '理解服务端最好的方式，是先看清静态站点和动态站点的分工',
    author: 'MDN Web Docs',
    views: '2.0k',
    time: '7m',
    publishDate: 'MDN 教程',
    sourceUrl: 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Server-side/First_steps/Introduction',
    cover: REMOTE_IMAGES.backendRack,
    coverGradient: ['rgba(231, 238, 255, 1)', 'rgba(212, 242, 240, 1)'],
    body: [
      'MDN 这篇文章非常适合拿来建立服务端的底层理解。它不是从某个框架切入，而是从 Web 请求最基本的生命周期开始讲：浏览器通过 HTTP 向服务器发请求，服务器处理请求后再返回响应。原文先解释了 URL、method、query string、POST data、cookies 这些基础元素，然后再把静态站点和动态站点的工作方式区分开。这种讲法很适合初学者，因为它能让你先理解后端存在的必要性，而不是一上来就被框架细节带走。',
      '文章对静态站点和动态站点的对比尤其关键。静态站点返回的是预先写好的固定内容，而动态站点则会在请求到来时，把数据库里的数据塞进 HTML 模板，再根据用户和场景动态生成响应。原文强调，大型网站几乎都会使用服务端代码去动态展示数据，因为这能让网站根据用户习惯和偏好做个性化内容分发，也能保存用户设置、订单信息、支付信息等关键数据。',
      '在“服务端和客户端是否一样”这一节，MDN 把前后端的边界讲得很清楚。客户端代码主要负责页面表现、布局、交互和表单校验，而服务端代码则负责决定返回什么内容、怎样校验请求、怎样读写数据库、怎样处理业务规则。它还特别提到，服务端几乎总是借助 Web framework 来做开发，因为像 HTTP server、session、authentication、templating、database access 这些能力，从零实现的成本非常高。',
      '如果你在准备后端方向，这篇文章最大的价值，是能帮你建立“后端不是接口集合，而是请求处理系统”的思维。很多人学后端只学到路由和 CRUD，但 MDN 这篇入门文能让你看到更底层的一层：用户请求是怎么进来的，服务端为什么需要模板、数据库和用户状态管理，前后端为什么会有明确分工。把这层逻辑想明白之后，再去学具体框架和项目实践，速度会快很多。',
    ],
  }),
  buildFeedCard({
    id: 'backend-setting-up-backend',
    roleId: 'backend',
    title: '把敏感逻辑放到后端，前后端分层才真正有意义',
    author: 'Codecademy',
    views: '1.6k',
    time: '4m',
    publishDate: '功能教程',
    sourceUrl: 'https://www.codecademy.com/article/wix-setting-up-a-backend',
    cover: REMOTE_IMAGES.backendRack,
    coverGradient: ['rgba(226, 236, 255, 1)', 'rgba(219, 242, 249, 1)'],
    body: [
      'Codecademy 这篇文章虽然是围绕 Wix 的 backend 功能来举例，但它其实讲清了一个非常通用的后端观念：后端最大的意义之一，就是把不应该暴露在前端的逻辑和数据处理放到服务端去执行。原文在示例里通过一个简单的 multiply 函数演示了前端如何调用 backend web module，然后再把结果回填到页面上。这个例子很轻，但它背后的架构含义很清楚。',
      '文章在解释代码时，逐行说明了 onReady、函数调用、Promise 返回值以及把数字转为字符串显示到页面上的过程。这里想表达的是，前端和后端并不是分开孤立存在的两套系统，而是前端负责发起请求、后端负责处理逻辑、最后再把结果交回前端展示。对初学者来说，这种“小链路跑通”的示例比只看概念定义更容易建立直觉。',
      '更关键的是原文在后面讲到，当前例子里的 multiply 很简单，但现实里后端往往要处理更复杂、也更敏感的事情。比如带有用户账户信息的函数、权限控制逻辑，或者规模很大的业务函数集合，都不适合直接暴露在前端代码里。把这些逻辑放进 backend，不只是为了“看起来专业”，而是为了保护敏感信息、控制访问权限，同时让整个代码结构更清晰可维护。',
      '如果你打算做后端项目，这篇文章很适合作为“为什么要做分层”的入门材料。很多学生项目表面上有前后端，其实业务逻辑还是混在页面里。原文用非常直接的方式提醒你：只要涉及敏感信息、复杂处理或需要长期维护的逻辑，就应该放在后端。这个意识一旦建立起来，你做服务端项目时的边界感会强很多，也更容易把项目讲得像一个真正的后端系统。',
    ],
  }),
  buildFeedCard({
    id: 'backend-web-frameworks',
    roleId: 'backend',
    title: '后端进阶的分水岭，往往是你会不会借助框架管理请求、数据库和安全',
    author: 'MDN Web Docs',
    views: '1.8k',
    time: '6m',
    publishDate: 'MDN 教程',
    sourceUrl: 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Server-side/First_steps/Web_frameworks',
    cover: REMOTE_IMAGES.backendRack,
    coverGradient: ['rgba(229, 238, 255, 1)', 'rgba(213, 243, 247, 1)'],
    body: [
      'MDN 这篇文章的价值在于，它把“为什么后端几乎总要用框架”讲得非常清楚。原文一开始先定义了 server-side web framework：这类框架的意义不是替你偷懒，而是把 URL 路由、数据库交互、session、用户授权、输出格式化以及 Web 安全等常见问题系统化地封装起来，让你更容易写、维护和扩展 Web 应用。对于后端初学者来说，这是从“会写接口”迈向“会搭系统”的关键认知。',
      '在“framework 能帮你做什么”这一节，文章强调框架让开发者不必总是和底层 HTTP 原语硬碰硬，而是可以用更高层、更可维护的方式处理请求和响应。这个点很重要，因为许多学生项目会误以为“纯手写底层细节”更体现能力，但真实开发里更看重的是稳定性、可读性和团队协作效率。框架恰好就是把这些高频共性问题做成了可复用的基础设施。',
      '文章还讨论了如何选择框架，这一段对求职也很有帮助。MDN 提到，选择框架要看学习成本、文档质量、社区活跃度、底层语言熟悉程度和生态支持，而不是只看“哪一个最火”。这意味着你选技术栈时应该考虑自己的项目目标和成长阶段。对于你现在这种准备求职的阶段，选一个文档成熟、生态清楚、能快速做出完整项目的框架，往往比盲目追最新名词更重要。',
      '如果把这篇文章转成可执行结论，其实很简单：后端学习不能停在语言和 CRUD，必须进入框架层。因为一旦涉及认证、数据库、模板、路由、接口组织和安全策略，你就已经进入真实 Web 应用开发了。你后面做第二志愿的后端准备时，可以直接把这一点落实到项目选择上，优先做一个用框架搭起来、结构清楚、边界明确的小服务，而不是继续堆零散练习。'
    ],
  }),
  buildFeedCard({
    id: 'backend-career-path',
    roleId: 'backend',
    title: '想把后端作为主线，就要接受它本质上是一条长项目链路',
    author: 'Codecademy',
    views: '1.7k',
    time: '5m',
    publishDate: '职业路径',
    sourceUrl: 'https://www.codecademy.com/learn/paths/back-end-engineer-career-path',
    cover: REMOTE_IMAGES.backendRack,
    coverGradient: ['rgba(228, 236, 255, 1)', 'rgba(219, 242, 247, 1)'],
    body: [
      'Codecademy 这条 Back-End Engineer 路径页虽然看起来像课程宣传，但它其实把后端学习这件事拆得很具体。原文先给出一个很直接的定义：后端开发者负责那些“藏在背后”的流程，包括 API 和数据库，它们共同支撑前端。随后它用 105 小时、60 个项目、41 个单元和 122 节课程去告诉读者，后端不是一门短平快技能，而是一条需要持续做项目、持续打基础的路线。',
      '很值得注意的是，这条路径并没有一上来就把人扔进某个框架，而是从开发环境、Web 基础、JavaScript 语法一路铺开。也就是说，哪怕最终目标是做后端，路径设计仍然要求你先把 Web 工作方式和编程基本功想明白。原文这种安排其实很合理，因为很多后端初学者的问题不在于不会写接口，而在于对 Web 请求、前后端关系、开发流程和错误处理并没有形成完整理解。',
      '页面还强调了项目数量和求职准备。60 个项目这个信息很关键，因为它说明后端技能很难只靠看文档堆出来，必须通过不断做东西去内化。再加上平台提供的面试模拟、job readiness checker 和认证机制，作者想表达的是：后端岗位准备从来都不只是“学技术”，而是技术、项目、表达、求职材料一起往前推。',
      '如果你把后端当作第二志愿，这条内容很适合转成自己的节奏规划。你未必真的要按 Codecademy 的整条路径走，但可以借它的结构去拆自己的准备顺序：先把 Web 和语言基础补稳，再做接口与数据库项目，再把项目讲法和面试表达同步准备起来。这样你后端方向的积累就不会碎，而会更像一条能真正投出去的职业主线。',
    ],
  }),
  buildFeedCard({
    id: 'embedded-roadmap',
    roleId: 'embedded',
    featured: true,
    featuredBadge: '嵌入式成长',
    title: '嵌入式学习最怕软硬件两边都只懂一点，路线图一定要有主线',
    author: 'Interrupt by Memfault',
    views: '2.2k',
    time: '6m',
    publishDate: '2025-07-25',
    sourceUrl: 'https://interrupt.memfault.com/blog/embedded-systems-roadmap-bridging-the-gap',
    cover: REMOTE_IMAGES.circuitBoard,
    coverGradient: ['rgba(255, 239, 218, 1)', 'rgba(221, 242, 233, 1)'],
    body: [
      'Memfault 这篇文章是作者围绕自己整理嵌入式学习路线图的经历写成的。开头他先回顾了自己在 2023 年之后重新梳理知识体系的原因：虽然已经在这个领域工作，但仍然觉得很多基础和新技术需要重新补课。于是他开始找现成的 embedded roadmap，结果发现都无法完全匹配自己的学习目标，这才促使他自己做了一份更完整的路线图。这个背景其实很能说明嵌入式的特点：它是一个需要持续回头补基础、持续跟上变化的领域。',
      '文章最关键的一段，是它把嵌入式定义为硬件和软件的交叉地带。作者指出，不管你原本来自电子、电气背景，还是来自软件工程、计算机背景，进入嵌入式后都几乎一定会发现自己有明显短板。硬件背景的人常常会在数据结构、编码效率、设计模式等软件问题上吃亏；软件背景的人则会在硬件接口、电信号、元器件理解、原理图和电路设计这些方面感到生疏。这种“任何人进来都会缺一块”的现实，正是嵌入式岗位学习难度高的根源。',
      '原文还提到，大学教育虽然提供了理论基础，但并不总能直接把学生送到真实的嵌入式工作场景里。很多学生毕业后会发现，自己知道原理，却不一定具备足够多的 hands-on project、联调经验和实操能力去应对企业里的任务。再加上网上的学习资源极其分散，书、课、教程到处都是，初学者很容易在“先补软件还是先补硬件”“先学单片机还是先学 RTOS”“先看协议还是先做项目”这种选择里迷失方向。作者认为，roadmap 的价值就在于此，它能帮你决定先后顺序，而不是把全部主题一次性摊到你面前。',
      '文章在介绍自己构建路线图时，也讲到了一个设计难点：如何既把硬件和软件分别展开，又能保留二者之间的交叉关系。因为很多嵌入式技能本来就很难绝对归类，比如一个看似软件的问题，背后往往需要硬件理解；一个看似硬件的现象，最后又会落到软件调试。作者最终把路线图结构化成硬件线、软件线以及交叉区域，并把更详细的学习资源继续放进 GitHub README 里，让读者既能看到全貌，也不会被图本身压垮。',
      '在“如何高效使用路线图”这部分，文章给出了非常实用的方法论。作者以 testing 为例，先建议读者从“为什么要学这个主题”开始，再去理解核心概念，然后再看 practical approach，比如 mocking、stubbing、unit testing、HIL testing 这些具体技术。他强调，学习任何嵌入式主题时，都要不断问自己几个问题：我当前想解决的具体问题是什么？这个资源解释得是否清楚？它是否真正贴近嵌入式场景里的硬件交互问题？这种筛选思路，比盲目囤资源更重要。',
      '文章最后把视角拉回职业成长本身。作者认为嵌入式成长既依赖 self-directed learning，也依赖 collaboration。你需要主动看资料、补基础、持续学习，也需要从社区、同事、技术分享、讨论群里吸收实践经验。同时还要关注 job market，观察招聘里真正反复出现的技能要求，避免把时间花在短期内用不上的方向上。对你来说，这篇文章最有价值的地方就在于它给嵌入式方向降了噪：不是所有东西都要同时学，而是先找一条主线，把它做深，再让作品和学习路径慢慢变得可展示、可求职。',
    ],
  }),
  buildFeedCard({
    id: 'embedded-unit-testing-basics',
    roleId: 'embedded',
    title: '嵌入式单元测试不是锦上添花，而是减少回归和死锁的基本手段',
    author: 'Interrupt by Memfault',
    views: '1.9k',
    time: '7m',
    publishDate: '2019-10-08',
    sourceUrl: 'https://interrupt.memfault.com/blog/unit-testing-basics',
    cover: REMOTE_IMAGES.circuitBoard,
    coverGradient: ['rgba(255, 240, 222, 1)', 'rgba(222, 241, 234, 1)'],
    body: [
      'Memfault 这篇文章从一个很常见的问题切入：很多嵌入式项目其实已经有成千上万行代码了，但单元测试却常常是被拖到很后面、甚至被完全忽略的一件事。作者认为这很危险，因为现代 firmware 早就不只是几个简单驱动，它还会涉及文件系统、BLE/Wi-Fi 协议栈、复杂数据结构，以及传感器算法等大量纯软件逻辑，而这些内容完全可以、也应该被 unit test。',
      '原文对 unit testing 的定义很清楚：把软件组件隔离出来，独立验证它们的正确性，并尽量覆盖关键路径、边界条件和失败场景。作者特别强调，如果结合 TDD 去做，嵌入式软件稳定下来所需的时间会明显下降，团队开发效率也会提升，很多功能 bug、控制流 bug、内存泄漏甚至 bootloop 这类致命问题，都会更早被拦住。对做底层开发的人来说，这种收益远不只是“测试更规范”这么简单。',
      '文章有一段很打动人的对比，叫“Life Before Unit Testing” 和 “Life After Unit Testing”。没有单元测试时，很多团队会接受回归反复出现、调试耗时过长、硬件测试麻烦、死锁和 HardFault 反复出现这种状态；而写了高覆盖率测试、模块边界清晰之后，很多新模块第一次烧到板子上就能工作，回归能在本地或 CI 里被立刻发现，绝大多数 firmware 测试只需要一分钟左右就能跑完。原文其实是在把单元测试从“附加项”重新定义为“开发体验改造器”。',
      '在后面的实操部分，文章又把 stub、fake、mock、CppUTest 等内容串了起来。它并不是要你给所有旧代码补测试，而是建议从新模块开始，把可测性和模块边界写进日常开发。对你如果以后想把嵌入式作为备选方向，这篇文章很值得读，因为它能帮你意识到：真正成熟的嵌入式开发并不只是会连板子、会写寄存器，还要能把软件逻辑抽离出来、在宿主机上跑测试、快速验证回归。这种工程习惯恰恰是企业最看重的部分。',
    ],
  }),
  buildFeedCard({
    id: 'embedded-unit-testing-mocks',
    roleId: 'embedded',
    title: '学会 mock 之后，很多硬件难复现的失败路径才能被认真测试',
    author: 'Interrupt by Memfault',
    views: '1.7k',
    time: '6m',
    publishDate: '2020-05-12',
    sourceUrl: 'https://interrupt.memfault.com/blog/unit-test-mocking',
    cover: REMOTE_IMAGES.circuitBoard,
    coverGradient: ['rgba(255, 238, 220, 1)', 'rgba(214, 237, 255, 1)'],
    body: [
      '这篇文章是前一篇 Unit Testing Basics 的延续，它一开始就指出，给嵌入式项目从零写测试往往会非常痛苦，因为嵌入式软件天然带着大量依赖：硬件驱动、操作系统、高层软件、通信协议栈全都混在一起，一个源文件背后可能挂着很多模块。也正因为依赖太多，很多人会误以为“这种东西根本没法认真测”。作者给出的答案就是：要学会把 mocks 当成工具箱里的关键工具。',
      '原文先回顾了 fake、stub、mock 三者的区别。fakes 是更简单但能工作的替代实现，stubs 是返回固定结果的简化实现，而 mocks 则是完全受单元测试控制的实现，可以预设返回值、检查参数、验证函数是否被调用。文章特别强调，mock 很适合去测试那些真实环境下很难、很危险、甚至根本不该反复触发的失败路径。比如某个车载软件模块在安全气囊触发时的行为，就不可能靠日常 QA 一遍遍去真测。',
      '在“Mocks in Detail”里，作者把 mock 的优势和代价都讲得很直。它最大的优势，是能把模块隔离得非常干净，让你去覆盖很多平时难碰到的 code path，朝着更高的 code coverage 靠近；但它的代价也很明显，就是会比较繁琐，因为每次调用、每个参数、每个返回值都要被明确配置或忽略。原文在这里反复提醒一点：测试里没有银弹，所有选择都是 trade-off，关键在于知道什么时候该用 mock。',
      '后面的例子则进一步说明了为什么很多嵌入式团队需要这套能力。作者展示了如何在 C/C++ 里为 malloc 一类依赖写 mock，如何用 expectOneCall 和参数校验来验证路径，还比较了 CppUMock、fff、CMock 等几种常见方案。对你来说，这篇文章最大的启发在于：嵌入式软件并不是只能靠真机联调来获得信心。很多逻辑路径、异常分支和边界条件，其实更适合在脱离硬件的测试环境里验证。能理解这点的人，做嵌入式项目时的工程感会明显更强。',
    ],
  }),
  buildFeedCard({
    id: 'embedded-arm-getting-started',
    roleId: 'embedded',
    title: '想从嵌入式入门，先抓住微控制器、Mbed 和快速原型这条线',
    author: 'Arm Education',
    views: '1.4k',
    time: '5m',
    publishDate: '2020-08-18',
    sourceUrl: 'https://developer.arm.com/community/education-hub/b/arm-education/posts/arm-edu-edx-embedded-systems-essentials',
    cover: REMOTE_IMAGES.circuitBoard,
    coverGradient: ['rgba(255, 241, 227, 1)', 'rgba(220, 239, 255, 1)'],
    body: [
      'Arm 这篇文章本质上是在介绍他们上线到 edX 的《Embedded Systems Essentials with Arm: Getting Started》课程，但它的价值不只是“课程宣传”，而在于它很好地解释了为什么嵌入式值得学、以及初学者最适合从什么角度切进去。原文首先指出，从当下的手机、可穿戴设备到 AI 和 5G 驱动的 IoT 设备，嵌入式系统已经是连接世界的基础构件，因此下一代工程师必须理解如何快速构建和部署现代嵌入式解决方案。',
      '在课程定位上，文章强调这是一个面向学生工程师和初学者的入门体系，目标是让学习者掌握嵌入式系统在现代计算场景中的意义，以及行业通用的 Arm 微控制器架构、特性和编程模型。换句话说，它不是一上来就让你陷进各种细碎板卡和协议，而是先把“嵌入式到底是什么”“微控制器怎么理解”“这套平台怎样被实际开发”三件事建立起来。',
      '很有意思的一点是，原文特别提到了 Mbed simulator。课程材料允许学习者直接在电脑上下载并使用 Mbed 模拟器，不需要先采购额外硬件。这一点对初学者非常友好，因为它大幅降低了试错成本，也降低了进入门槛。很多人对嵌入式望而却步，往往不是因为内容本身，而是因为一开始就被硬件采购、环境配置和设备连接绊住了。Arm 在这里强调的正是“先快速原型，再逐步深入”。',
      '对你这样的学生来说，这篇文章很适合被当作嵌入式入门方向的路线提醒。它清楚地说明，嵌入式学习完全可以从理解系统意义、掌握微控制器基础、借助模拟器快速原型开始，而不必一上来就被复杂硬件门槛吓退。把这个思路跟你现有的软件研发基础结合起来，其实非常适合拿来做第三方向的差异化储备。',
    ],
  }),
  buildFeedCard({
    id: 'embedded-device-logging',
    roleId: 'embedded',
    title: '嵌入式日志不是随手打印，真正有用的是一开始就想清楚谁来看、存多久、怎么解析',
    author: 'Interrupt by Memfault',
    views: '1.8k',
    time: '6m',
    publishDate: '2023-12-20',
    sourceUrl: 'https://interrupt.memfault.com/blog/device-logging',
    cover: REMOTE_IMAGES.circuitBoard,
    coverGradient: ['rgba(255, 240, 224, 1)', 'rgba(221, 241, 235, 1)'],
    body: [
      'Memfault 这篇文章把日志这件事讲得非常“工程化”。原文一开始就指出，嵌入式设备做日志和服务器完全不同，因为设备在内存、存储、带宽和算力上都更受限，而且一次日志格式设计错误，可能要等下个固件版本才能修。也就是说，日志不是调试时顺手 `printf` 一下那么简单，它本身就是产品设计的一部分。',
      '文章先讨论 Log Collection，强调在开始写日志前就要决定日志缓存大小、采集方式、现场采集还是远程采集、在什么事件发生时触发收集。这个顺序很关键，因为它提醒开发者：日志的价值不在“有没有打印”，而在于问题发生时你能否真正拿到足够的上下文。如果设备出问题时根本拿不到关键记录，再漂亮的日志语句也没有意义。',
      '在 Logging Best Practices 部分，作者提出了几个特别实用的原则：记住目标读者是谁、提升可读性、必要时用错误码或引用外部说明文档、尽量让日志适合机器解析。尤其是 structured logs 这一点，很值得做嵌入式的人认真吸收。它说明日志不只是给人看，还应该服务于自动分析、聚合和排障流程，这种思路会直接决定你后续维护设备时的效率。',
      '如果你未来把嵌入式作为备选方向，这篇文章能帮你迅速从“会写驱动”往“会维护设备”上提升一个层级。因为真实嵌入式开发不只是在板子上把功能点亮，更重要的是设备出了问题以后你能不能有办法追踪、定位和复盘。日志系统设计得越早、越清楚，后面项目的工程感就越强，而这正是很多学生作品最缺的一块。',
    ],
  }),
  buildFeedCard({
    id: 'embedded-watchdog-best-practices',
    roleId: 'embedded',
    title: '看门狗不是最后才补的保险，而是嵌入式系统稳定性的底线',
    author: 'Interrupt by Memfault',
    views: '1.9k',
    time: '7m',
    publishDate: '2020-02-18',
    sourceUrl: 'https://interrupt.memfault.com/blog/firmware-watchdog-best-practices',
    cover: REMOTE_IMAGES.circuitBoard,
    coverGradient: ['rgba(255, 237, 219, 1)', 'rgba(216, 238, 255, 1)'],
    body: [
      '这篇文章把 watchdog 从“老生常谈的概念”重新拉回到了实战场景。原文先解释，看门狗本质上是 MCU 里的一个独立计数器，如果软件在规定时间内没去喂它，硬件就会自动复位系统。这看起来像是基础知识，但作者接着点出了它真正的价值：当设备因为死循环、硬件卡死、任务饥饿或互斥锁死锁而挂住时，看门狗往往是最后一道还能让系统恢复的防线。',
      '在“为什么要用 watchdog”这一节，文章列出的挂死场景非常典型，包括内存损坏、外设无响应、任务死锁、高优先级任务长期占满 CPU 等。这一段最有说服力的地方在于，它把很多初学者容易觉得“极端”的问题说成了嵌入式里非常日常的风险。换句话说，不加 watchdog 不是一种简化，而是一种把不可控风险留在产品里的做法。',
      '原文后半段开始进入真正有用的部分：它不是停在概念解释，而是走到具体实现，包括如何读数据手册、如何理解配置寄存器复位行为、超时怎么选、如何判断 watchdog reset 是否发生、如何在 FreeRTOS 场景里进一步做 software watchdog 和 task watchdog。作者的思路很清晰，看门狗不是“打开就完事”，而是要和系统调试、故障定位、任务设计一起考虑。',
      '这篇内容对你做嵌入式储备很有价值，因为它能帮助你建立一种更成熟的底层系统观。很多学生做板级项目时只在意功能跑没跑起来，但企业更在意系统挂死以后怎么办、有没有恢复策略、有没有定位信息。watchdog 恰好把“系统设计是否可靠”这件事暴露得很明显。你哪怕只是做一个小项目，只要能讲清 watchdog 该怎么设计、为什么需要它，整个人的工程成熟度都会上去。'
    ],
  }),
  buildFeedCard({
    id: 'direction-programmer-types',
    roleId: 'direction',
    featured: true,
    featuredBadge: '方向判断',
    title: '探索方向时，先分清你更想做系统实现，还是更想做前台体验',
    author: 'Codecademy',
    views: '1.2k',
    time: '4m',
    publishDate: '方向文章',
    sourceUrl: 'https://www.codecademy.com/article/what-different-kinds-of-programmers-do-videos',
    cover: REMOTE_IMAGES.careerNotebook,
    coverGradient: ['rgba(236, 234, 255, 1)', 'rgba(213, 243, 249, 1)'],
    body: [
      'Codecademy 这篇文章的出发点很直接，就是帮刚接触技术方向的人先分清“程序员岗位到底有哪些大类”。原文先把职业路径分成 Software Engineering 和 Data Science 两个大方向，然后从 Software Engineering 里继续往下拆，列出 Full-Stack、Front-End、Back-End 三种典型的软件工程岗位。虽然这篇文章篇幅不算长，但它对于还没完全确定自己方向的人非常有用，因为它先做的不是讲技术细节，而是帮助读者建立岗位地图。',
      '在 Software Engineering 这一部分，原文把软件工程描述成“设计并创建解决现实问题的软件”的职业路径。这个定义其实很关键，因为它把软件工作从“学语言、写代码”提升到了“解决问题、做产品能力落地”的层面。随后文章提示读者，不同类型的软件工程师关注的软件部分并不一样，有的人更偏前端体验，有的人更偏全栈统筹，也有人更偏后端服务和数据处理。也就是说，软件岗位的差别首先体现在问题域，而不是体现在某个框架名词上。',
      '文章后面给出的建议很朴素，但非常适合用来做方向判断。它认为，选职业方向最好的办法之一，是先“try a little of them yourself”，也就是先自己试一点，再决定是否值得长期投入。另一个办法，则是去完成一些课程里的 overview 和 sample，先让自己对不同路径的日常工作方式有直观感受。换成更接地气的话说，方向不是靠想出来的，而是靠体验筛出来的。',
      '把这篇文章放到你的首页帖子里，价值就在于它能承担“探索方向”这个角色。你现在其实已经明显偏软件研发主线了，但还需要继续确认自己更适合偏系统实现、偏服务端逻辑，还是更喜欢其他技术分工。原文给出的思路正好能落成动作：不要先问哪个方向最热，而是先做几个小样例，看看自己更愿意把时间花在哪一种问题上。这个判断一旦稳定下来，后面能力画像和岗位排序也会更自然。',
    ],
  }),
  buildFeedCard({
    id: 'direction-fullstack-vs-backend',
    roleId: 'direction',
    title: '在全栈和后端之间做选择，关键不是哪个更热，而是你想承担多大的技术边界',
    author: 'roadmap.sh',
    views: '1.5k',
    time: '5m',
    publishDate: '方向对比',
    sourceUrl: 'https://roadmap.sh/full-stack/vs-backend',
    cover: REMOTE_IMAGES.careerNotebook,
    coverGradient: ['rgba(236, 233, 255, 1)', 'rgba(220, 242, 247, 1)'],
    body: [
      'roadmap.sh 这篇对比文很适合放在“探索方向”里，因为它没有停留在抽象定义，而是直接把 Full Stack 和 Backend 按照 focus、roles、technologies、skill sets、learning curve 和 job openings 这些维度拆开比较。原文一开始就说得很清楚：全栈的核心是同时覆盖前端和后端，而后端则专注于服务器侧。这听起来像常识，但很多人在求职准备时正是卡在这里，边界没想清楚，最后什么都碰一点却没有一条真正成型的主线。',
      '文章在职责差异上给出的判断很有参考价值。全栈意味着更宽的 ownership，要同时照顾页面、接口、数据和前后端联动；后端则把注意力集中在数据库、安全、缓存、API 和服务端逻辑上。对学生来说，这实际上就是两种不同的成长路线：一种更偏“统筹整个应用”，另一种更偏“把服务器端问题做深”。你现在如果已经明显更偏软件研发和系统实现，这种拆分会很有帮助。',
      '原文还讨论了技术栈与学习曲线。全栈需要同时接触 HTML、CSS、前端框架以及后端语言和框架，覆盖面更广；后端则更聚焦在服务端语言、框架和数据层。它还提到，后端相对全栈会更容易聚焦一些。这一点对当前阶段尤其重要，因为你时间和精力都有限，选一个更聚焦的方向往往比“什么都想会”更现实。',
      '把这篇内容转成你的实际决策，其实结论很明确：如果你已经对系统实现、C++、Linux、服务逻辑更有兴趣，那后端会比全栈更贴合你现阶段的能力结构；如果未来想扩大技术边界，再从后端往全链路走也不迟。方向判断最怕的是被岗位名称带着跑，这篇文章的价值就在于它把差异拆成了可比较的维度，让你能更理性地做选择。',
    ],
  }),
  buildFeedCard({
    id: 'direction-fullstack-career-path',
    roleId: 'direction',
    title: '如果你还不确定只做后端还是做更宽的开发岗位，可以先看全栈路径到底要求什么',
    author: 'Codecademy',
    views: '1.4k',
    time: '5m',
    publishDate: '职业路径',
    sourceUrl: 'https://www.codecademy.com/learn/paths/full-stack-engineer-career-path',
    cover: REMOTE_IMAGES.careerNotebook,
    coverGradient: ['rgba(235, 234, 255, 1)', 'rgba(214, 242, 248, 1)'],
    body: [
      'Codecademy 这条 Full-Stack Engineer 路径页很适合用来做“方向校准”。原文用非常直白的方式定义全栈：从前端到后端，把一个项目从开始做到结束。页面同时给出了一组很有冲击力的数据，像 150 小时、96 个项目、51 个单元，目的其实不是强调学习量有多大，而是提醒读者，全栈不是“顺手多学一点后端”或者“顺手碰一下前端”，而是一条覆盖面明显更宽的路线。',
      '这条路径的教学顺序也很有说明力。它不是一上来就讲服务端，而是从 HTML、CSS、本地开发、部署、前端基础一路展开，再逐步进入后端和连接两端的能力。这意味着全栈路线要求你同时建立界面理解、交互实现、服务端处理以及部署协同的整体视角。对于还在探索的人来说，这能帮助你判断自己到底喜欢“完整链路的成就感”，还是更喜欢深入某一侧的问题。',
      '页面后半段还特别强调 portfolio projects、interview simulator、job-readiness checker 和 certification。它想传递的其实是一个很现实的信息：全栈路线的求职门槛不只是知识面广，还包括你要拿出跨端项目来证明自己能把前后端串起来。也就是说，如果选全栈，未来你准备作品集和面试时，压力和收益都会更综合。',
      '对你当前的状态来说，这篇内容最大的价值不一定是让你转去做全栈，而是帮你确认“自己是不是更适合先走一条更窄更深的主线”。如果你看完全栈要求后，更确定自己想先把服务端、系统实现和工程能力做扎实，那这篇文章同样完成了它的任务。方向判断很多时候不是为了扩张，而是为了更明确地收拢。'
    ],
  }),
];
